apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Values.mongo.deployment}}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{.Values.mongo.name}}"
        version: "{{.Values.mongo.versionLabel}}"
    spec:
      containers:
      - name: "{{.Values.mongo.name}}"
        image: "{{.Values.mongo.image}}:{{.Values.mongo.imageTag}}"
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.mongo.name}}"
  labels:
    app: "{{.Values.mongo.name}}"
spec:
  type: "{{.Values.mongo.serviceType}}"
  ports:
  - name: http
    port: 27017
    targetPort: 27017
  selector:
    app: "{{.Values.mongo.name}}"